### ISSUE TITLE
Scrolling in "new" is buggy on mac

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#78]
when the mouse hovers over a simulation in the "new" menu, scrolling stops.

**Comment by dragly** [comment]
@andreavs Could you double-check that this is fixed by commit 1d99ae3? Flickable was replaced by ScrollView, which should make scrolling stable on both mobile and desktop.

**Comment by andreavs** [comment]
Still does not work. Scrolling works in left-right direction, but not up-down.

**Comment by andreavs** [comment]
Problem can be "fixed" by setting interactive: false on the horizontal Flickable object.

**Comment by andreavs** [comment]
Fixed in commit 97561c516f637142b2c71cc8f3b46a49e2f59551.
